name: Test

on:
  workflow_run:
    workflows: ["Train"]
    types:
      - completed

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    needs: training
    strategy:
      matrix:
        tag: [latest]

    steps:
    - name: Pull Docker image
      run: docker pull docker.io/nainagurung92/cicd_assignment92:${{ matrix.tag }}

    - name: Check score
      run: |
        score=$(docker run docker.io/nainagurung92/cicd_assignment92:${{ matrix.tag }} | awk '{print $NF}')
        if (( $(echo "$score >= 0.50" | bc -l) )); then echo "Sufficient Accuracy"; else echo "Insufficient Accuracy" && exit 1; fi

  standalone-job:
    runs-on: ubuntu-latest
    steps:
    - name: Do something
      run: echo "This is a standalone job"
