name: Train

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'data/**'
      - 'requirements.txt'
      - 'README.md'

  workflow_dispatch:
     inputs:
      Test:
        description: 'Test workflow which will be triggered'
        required: true
        default: 'Test'


permissions:
  contents: read

jobs:
  training:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          docker.io/nainagurung92/cicd_assignment92:latest

    - name: Train Completed, Trigger Workflow Test
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.ACTIONS_KEY }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/nainagurung92/CICD_Assignment/actions/workflows/92723961/dispatches \
          -d '{"ref":"main"}'
